@startuml Покупка прикорма

start
:Пользователь подплывает к магазину на берегу;
:Приложение выводит подсказку к использованию кнопки Е;
:Пользователь нажимает кнопку Е;
repeat :Приложение отображает интерфейс магазина;
    :Пользователь выбирает опцию покупки прикорма;
    if (Пользователь имеет достаточно монет) then (Да)
        :Приложение выводит сообщение о покупке;
        :Количество денег уменьшается в соответствии со стоимостью прикорма;
        :Приложение добавляет прикорм в инвентарь игрока;
    else (Нет)
        :Приложение выводит сообщение о недостаточном количестве монет;
    endif
    if (Пользователь нажимает кнопку Esc или E) then (Да)
        break
    endif
repeat while (Кнопка Esc или E не нажаты)
:Приложение закрывает магазин;
stop

@enduml
