@startuml Покупка улучшений

start
:Пользователь подплывает к магазину на берегу;
:Приложение выводит подсказку к использованию кнопки Е;
:Пользователь нажимает кнопку Е;
repeat :Приложение отображает интерфейс магазина;
    :Пользователь выбирает опцию улучшения лодки или опцию улучшения удочки;
    if (Пользователь имеет достаточно монет) then (Да)
        :Приложение производит улучшение;
        :Количество денег уменьшается в соответствии со стоимостью улучшения;
        :Приложение выводит сообщение об улучшении;
    else (Нет)
        :Приложение выводит сообщение о недостаточном количестве монет;
    endif
    if (Пользователь нажимает кнопку Esc или E) then (Да)
        break
    endif
repeat while (Кнопка Esc или E не нажаты)
:Приложение закрывает магазин;
stop

@enduml
