@startuml
state "Покупка улучшений" as UpgradeShop {
    [*] --> ВывестиПодсказку
    ВывестиПодсказку --> ВывестиИнтерфейсМагазина : Кнопка Е
    ВывестиИнтерфейсМагазина --> ВыборУлучшения : Выбрана опция улучшения
    state ПроверитьДеньги <<ПроверитьДеньги>>
    ВыборУлучшения --> ВывестиИнтерфейсМагазина : Нажата кнопка Esc
    ВыборУлучшения --> УлучшениеЛодки
    ВыборУлучшения --> УлучшениеУдочки
    УлучшениеЛодки --> ПроверитьДеньги : Достаточно денег?
    УлучшениеУдочки --> ПроверитьДеньги : Достаточно денег?
    ПроверитьДеньги --> Улучшение : Улучшение куплено, уменьшение денег
    Улучшение --> ВывестиСообщениеОбУлучшении : Достаточно денег, наживка куплена
    ПроверитьДеньги --> ВывестиСообщениеОбОшибке : Денег недостаточно
    ВывестиИнтерфейсМагазина --> ЗакрытьМагазин : Нажата кнопка Esc
}
@enduml
