@startuml
state "Покупка наживки" as ПокупкаНаживки {
  [*] --> ВывестиПодсказку : Пользователь подплывает
  ВывестиПодсказку --> ВывестиИнтерфейсМагазина : Нажата кнопка E
  ВывестиИнтерфейсМагазина --> КупитьНаживку : Выбрана опция покупки наживки
  state ПроверитьДеньги <<ПроверитьДеньги>>
  КупитьНаживку --> ПроверитьДеньги : Проверка количества денег
  ПроверитьДеньги --> ВывестиСообщениеОПокупке : Достаточно денег, наживка куплена
  ПроверитьДеньги --> ВывестиСообщениеОбОшибке : Денег недостаточно
  ВывестиИнтерфейсМагазина --> ЗакрытьМагазин : Нажата кнопка Esc
}
@enduml