@startuml
state "Покупка прикорма" as ПокупкаПрикорма {
  [*] --> ВывестиПодсказку : Пользователь подплывает
  ВывестиПодсказку --> ВывестиИнтерфейсМагазина : Нажата кнопка E
  ВывестиИнтерфейсМагазина --> КупитьПрикорм : Выбрана опция покупки прикорма
  state ПроверитьДеньги <<ПроверитьДеньги>>
  КупитьПрикорм --> ПроверитьДеньги : Проверка количества денег
  ПроверитьДеньги --> ВывестиСообщениеОПокупке : Достаточно денег, прикорм куплен
  ПроверитьДеньги --> ВывестиСообщениеОбОшибке : Денег недостаточно
  ВывестиИнтерфейсМагазина --> ЗакрытьМагазин : Нажата кнопка Esc
}
@enduml