@startuml
state "Миниигра ловли рыбы" as Fishing {
  [*] --> Подплыть_к_рыбному_месту
  Подплыть_к_рыбному_месту --> Начало_рыбалки : Кнопка Е
  Начало_рыбалки --> Игровой_процесс : Клик мыши
  Игровой_процесс --> Засечка : Зажать ЛКМ
  Засечка --> Вытащить_удочку : Удержать ЛКМ нужное время
  Засечка --> Поражение : Отпустить ЛКМ раньше истечения нужного времени
  Вытащить_удочку --> Победа : Рыба поймана
  Игровой_процесс --> Поражение : Рыба не поймана
}
@enduml