@startuml
state "Продажа рыбы" as ПродажаРыбы {
  [*] --> ВывестиПодсказку : Пользователь подплывает
  ВывестиПодсказку --> ВывестиИнтерфейсМагазина : Нажата кнопка E
  ВывестиИнтерфейсМагазина --> ВыборРыбы : Вывести меню продажи рыбы
  state choise1 <<choice>>
  state ВыборРыбы
  ВыборРыбы --> ВывестиИнтерфейсМагазина : Нажата кнопка Esc
  ВыборРыбы --> ВывестиСообщение : Рыба продана

  ВывестиСообщение --> choise1 : Осталась ли ещё рыба в инвентаре?
  choise1 --> ВыборРыбы : Да, перейти к продаже следующей рыбы
  choise1 --> ВывестиИнтерфейсМагазина : Нет
  ВывестиИнтерфейсМагазина --> ЗакрытьМагазин : Нажата кнопка Esc
}
@enduml