@startuml
participant Пользователь
participant Игра
participant Лодка
participant Магазин
participant Удочка
participant Инвентарь

loop GameLoop
    Пользователь -> Игра: Нажимает кнопки WASD
    Игра -> Лодка: Перемещает лодку
    Игра -> Миниигра: Генерирует рыбное место
    
    loop Миниигра ловли рыбы
        Пользователь -> Игра: Подплывает к рыбному месту
        Пользователь -> Игра: Нажимает E
        Игра -> Миниигра: Открывает миниигру ловли рыбы
        Пользователь -> Миниигра: Ловит рыбу
        Миниигра -> Инвентарь: Добавляет рыбу в инвентарь
    end
    
    loop Продажа рыбы
        Пользователь -> Игра: Подплывает к магазину/островам
        Пользователь -> Игра: Нажимает E
        Игра -> Магазин: Открывает магазин
        Пользователь -> Магазин: Выбирает рыбу
        Магазин -> Инвентарь: Удаляет рыбу из инвентаря
        Магазин -> Пользователь: Добавляет деньги
    end
    
    loop Покупка улучшений удочки
        Пользователь -> Игра: Подплывает к магазину
        Пользователь -> Игра: Нажимает E
        Игра -> Магазин: Открывает магазин
        Пользователь -> Магазин: Выбирает улучшение
        Магазин -> Пользователь: Снимает деньги
        Магазин -> Удочка: Улучшает удочку
    end

    loop Покупка улучшений лодки
        Пользователь -> Игра: Подплывает к магазину
        Пользователь -> Игра: Нажимает E
        Игра -> Магазин: Открывает магазин
        Пользователь -> Магазин: Выбирает улучшение
        Магазин -> Пользователь: Снимает деньги
        Магазин -> Лодка: Улучшает лодку
    end

    loop Покупка наживки
        Пользователь -> Игра: Подплывает к магазину
        Пользователь -> Игра: Нажимает E
        Игра -> Магазин: Открывает магазин
        Пользователь -> Магазин: Выбирает наживку
        Магазин -> Пользователь: Снимает деньги
        Магазин -> Инвентарь: Добавляет наживку
    end
    
    loop Покупка прикормки
        Пользователь -> Игра: Подплывает к магазину
        Пользователь -> Игра: Нажимает E
        Игра -> Магазин: Открывает магазин
        Пользователь -> Магазин: Выбирает прикормку
        Магазин -> Пользователь: Снимает деньги
        Магазин -> Инвентарь: Добавляет прикормку
    end
    
    loop Открытие инвентаря
        Пользователь -> Игра: Нажимает E
        Игра -> Инвентарь: Открывает инвентарь
    end
end
@enduml