@startuml
participant Пользователь
participant Игра
participant Лодка
participant Рыба
participant Магазин
participant Удочка
participant Наживка
participant Прикорм
participant Инвентарь

loop GameLoop
    Пользователь -> Игра: Нажимает кнопки WASD
    Игра -> Лодка: Перемещает лодку
    Игра -> Рыба: Генерирует рыбу
    
    loop Пока рыба не поймана
        Пользователь -> Игра: Нажимает E
        Игра -> Магазин: Открывает меню
        Пользователь -> Магазин: Нажимает купить приманку
        Магазин -> Инвентарь: Добавляет приманку
        Пользователь -> Игра: Нажимает на рыбу
        Игра -> Удочка: Перемещает крючок
        Пользователь -> Игра: Удерживает ЛКМ
        Игра -> Удочка: Удерживает рыбу
    end
    
    loop Пока удочка не улучшена
        Пользователь -> Игра: Нажимает E
        Игра -> Магазин: Открывает меню
        Пользователь -> Магазин: Нажимает купить улучшение
        Магазин -> Удочка: Улучшает удочку
    end
    
    loop Пока не куплен прикорм
        Пользователь -> Игра: Нажимает E
        Игра -> Магазин: Открывает меню
        Пользователь -> Магазин: Нажимает купить прикорм
        Магазин -> Инвентарь: Добавляет прикорм
    end
    
    Пользователь -> Игра: Нажимает E
    Игра -> Инвентарь: Открывает инвентарь
end
@enduml