@startuml Диаграмма классов

class Player {
    -position: Coordinates
    +move(direction: Direction, coordinates: Coordinates)
}

class Inventory {
    +display()
    -contents: Set<Money, Lure, Bait>
    -fish_list: List<Fish>
    +add(fish: Fish)
    +del(fish: Fish)
}

class Object {
    - amount: int
    + increase_amount(amount)
    + reduce_amount(amount)
    + display(surface: Coordinates: Coordinates, size, amount)
}

class Money {}

class Fish {
    -position: Coordinates
    +draw(surface: Coordinates, size)
}
class Fishtype {
    -type: str
    -speed: float
    -price: int
}

class Lure {
    +useTime
    -buff: float
}

class Bait {
    -buff: float
}

class Coordinates {
    -x: float
    -y: float
}

class Direction {
    -UP: float
    -DOWN: float
    -LEFT: float
    -RIGHT: float
}

class Boat {
    -speed: float
    +draw(surface: Coordinates, size)
}

class Rod {
    -level: float
    +displayLvl(surface: Coordinates, size, level)
}

class MiniGame {
    -position: Coordinates
    +display()
    +moveFish(fish: Fish, direction: Direction, coordinates: Coordinates)
    +moveCursor(direction: Direction)
    +holdCursor(time: Time)
    +catchFish(fish: Fish)
    +useBait(bait: Bait)
}

class Shop {
    -position: Coordinates
    +display()
    +draw(surface: Coordinates, size)
}

class Island {
    -position: Coordinates
    +display()
    +draw(surface: Coordinates, size)
}

class SellFish {
    +sell(fish: Fish)
}

class UpgradeBoat {
    +upgrade(boat: Boat)
}

class UpgradeRod {
    +upgrate(rod: Rod)
}

class BuyBait {
    +buy(bait: Bait)
}

class BuyLure {
    +buy(lure: Lure)
}



Player --> Inventory : Open
Inventory --> Object
Inventory <-- Fish
Lure --|> Object
Bait --|> Object
Money --|> Object
Fish --> MiniGame
Player --> Boat
Player ---> MiniGame : Play
MiniGame --> Inventory 
Player --> Island : Open
Fishtype --> Fish
BuyBait --> Inventory
BuyLure --> Inventory
SellFish --> Inventory
UpgradeBoat --> Boat
UpgradeRod --> Rod
Shop o-- UpgradeBoat
Shop o-- UpgradeRod
Shop o-- BuyBait
Shop o-- BuyLure
Shop --|> Island
Island o-- SellFish

@enduml