@startuml Диаграмма объектов
object Player {
  + movePlayer(direction: Direction)
  + collectMoney(money: Money)
  + collectFish(fish: Fish)
  + useBait(bait: Bait)
  + useLure(lure: Lure)
}

object Boat {
  + moveBoat(direction: Direction)
  + upgradeBoat(upgrade: Upgrade)
}

object MiniGame {
  + display()
  + moveCursor(direction: Direction)
  + holdCursor(time: Time)
  + catchFish(fish: Fish)
}

object Shop {
  + display()
  + sellFish(fish: Fish)
  + buyBait(bait: Bait)
  + buyLure(lure: Lure)
  + upgradeBoat(upgrade: Upgrade)
}

object Inventory {
  + display()
}

object Money {
    - amount
}

object Fish {
  + display(surface: Coordinates, size)
}

object Lure {
  + useTime
  - buff: float
}

object Bait {
  - buff: float
}

object Upgrade {
  + upgrade(target: object)
}

object Coordinates {
  - x: float
  - y: float
}

object Direction {
  - UP: float
  - DOWN: float
  - LEFT: float
  - RIGHT: float
}

Player -up- Boat
Player -up- MiniGame
MiniGame -up- Inventory
Player -up- Shop
Player -up- Inventory
Fish -up- Coordinates
MiniGame -up- Coordinates
Player -up- Direction
MiniGame -up- Direction

@enduml