@startuml Продажа рыбы

start
:Пользователь подплывает к магазину или острову;
:Приложение выводит подсказку к использованию кнопки Е;
:Пользователь нажимает кнопку Е;
repeat :Приложение отображает интерфейс магазина;
    if (Пользователь выбирает опцию продажи рыбы) then (Да)
        repeat :Приложение отображает меню выбора рыбы;
            if (Пользователь выбирает рыбу для продажи) then (Да)
                :Количество денег увеличивается в соответствии со стоимостью проданной рыбы;
                :Приложение выводит сообщение о продаже рыбы;
            endif
            if (Пользователь нажимает кнопку Esc) then (Да)
                break
            endif
        repeat while (Кнопка Esc не нажата)
        :Приложение закрывает меню выбора рыбы;
    endif
    if (Пользователь нажимает кнопку Esc или E) then (Да)
        break
    endif
repeat while (Кнопка Esc или E не нажаты)
:Приложение закрывает магазин;
stop

@enduml
